import sys,time
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
import nbformat as nb
from nbclient import NotebookClient
from jupyter_client import KernelManager
from annni.stage6_followup import *
book=nb.v4.new_notebook();book.metadata['kernelspec']={'display_name':'Python locked scientific environment','language':'python','name':'python3'}
book.cells=[nb.v4.new_markdown_cell('# Stage 6 定向补全：B3 窗口与等 CNOT-shots\n\n本 notebook 读取本轮已经保存的数值实验；不会把这些历史读取算成现场重新采样。最后一个检查单元会实际从联合计数重建一个估计量。图中经验区间不是统计置信区间，RN 特征不是精确热力学相界。'),nb.v4.new_code_cell("from pathlib import Path\nimport os,sys,json,numpy as np\nroot=next(p for p in [Path.cwd(),*Path.cwd().parents] if (p/'annni/stage6_followup.py').exists())\nos.chdir(root);sys.path.insert(0,str(root))\nfrom annni.stage6_followup import *\nfrom IPython.display import display,Image\nconfig=cfg()\nprint(config['run_id'],config['started_utc'],config['deadline'])"),nb.v4.new_markdown_cell('## 已保存的执行与预算审计\n\n所有噪声和预算结果来自冻结的 B3 门表。等 CNOT-shots 并不等同于单比特门数、测量设置或硬件时间相同。'),nb.v4.new_code_cell("stats=read(OUT/'verification/execution_statistics.json')\nprint(json.dumps(stats,indent=2))\nprint({b:equal_gate_shots(b) for b in config['equal_gate_base_budgets']})"),nb.v4.new_code_cell("summary=read(OUT/'equal_gate_budget/summary.json')\nfor r in summary:\n    if r['cohort']=='all_B':\n        print(r['mode'],r['budget'],r['p'],r['method'],r['points'],r['MSE_ED_mean'],r['CNOT_shots_all32'])"),nb.v4.new_markdown_cell('## 六条窗口的完整曲线\n\n相同窗口跨 p 使用相同纵轴；保留端点、所有峰、结构切换和制态失败。'),nb.v4.new_code_cell("display(Image(filename=str(OUT/'figures/six_window_orders.png')))\ndisplay(Image(filename=str(OUT/'figures/six_window_responses.png')))"),nb.v4.new_markdown_cell('## 匹配、曲线问题与真实资源\n\n32 次重复先在物理窗口内归一化。κ=.5 的未分辨不记作零位移。'),nb.v4.new_code_cell("display(Image(filename=str(OUT/'figures/coverage_and_issues.png')))\ndisplay(Image(filename=str(OUT/'figures/equal_resource_MSE_cost.png')))\ndisplay(Image(filename=str(OUT/'figures/equal_resource_window_features.png')))"),nb.v4.new_markdown_cell('## 本次 notebook 现场轻量重算\n\n以下重新从一个保存的整 bitstring 多项分布计数构造二阶 ZNE，核对整数 CNOT-shots；没有执行新的 VQE 或完整密度扫描。'),nb.v4.new_code_cell("record=next(read(p) for p in (OUT/'measurements').glob('*.json') if (lambda r:r['mode']=='equal_gate' and r['method']=='zne_quadratic')(read(p)))\na=np.load(ROOT/record['archive']);counts=a['counts'][0];offset=0;vs=[]\nfor s in record['settings']:\n    dist={b:counts[offset+i]/num for i,(b,num) in enumerate(zip(s['bases'],s['allocations']))}\n    offset+=len(s['bases']);vs.append(estimated_vector(dist,8,False)[0])\nrecomputed=RICHARDSON@np.array(vs)\nnp.testing.assert_allclose(recomputed,a['samples'][0],atol=1e-12)\nG=sum(sum(s['allocations'])*r['cnots'] for s,r in zip(record['settings'],record['probabilities']))\nassert G==record['CNOT_shots_per_repeat']\nprint('Fresh count reconstruction passed; max error=',float(max(abs(recomputed-a['samples'][0]))),'G=',G)"),nb.v4.new_markdown_cell('## 解释范围\n\nMSE 改善不自动代表峰位置或相标签恢复；D3 只在声明的独立物理标签资格集上评估。新曲线审阅字段是本轮解释性检查，不能回写成历史预注册规则。完整逐点结果、失败重复与资源成本见 REPORT.md 和 decision.json。')]
path=OUT/'followup.ipynb';nb.write(book,path);manager=KernelManager(kernel_name='python3');manager.kernel_spec.argv=[sys.executable,'-m','ipykernel_launcher','-f','{connection_file}'];t=time.perf_counter();client=NotebookClient(book,km=manager,timeout=180,resources={'metadata':{'path':str(ROOT)}});client.execute();manager.shutdown_kernel(now=True);nb.validate(book);nb.write(book,path);dump(OUT/'verification/notebook_execution.json',dict(executed_utc=datetime.now(timezone.utc).isoformat(),python=sys.executable,seconds=time.perf_counter()-t,sha256=sha(path),code_cells=sum(c.cell_type=='code' for c in book.cells),errors=[o for c in book.cells if c.cell_type=='code' for o in c.outputs if o.output_type=='error']));print('Executed notebook')
