from pathlib import Path
import json,html
ROOT=Path(__file__).resolve().parents[1];S=ROOT/'submission';s=json.loads((S/'statistics.json').read_text())
slides=[
('Why an exact clean diagram is not enough',None,'N=8 periodic ANNNI | prescribed CNOT-target noise | preparation protocol matters',"Our question is not just whether a clean phase diagram looks plausible. The challenge asks what gate noise changes. To answer that, we need a preparation circuit whose ideal error is measured, a specified gate sequence, and a way to separate physical signal from preparation choices. We study eight periodic spins, so our results concern finite-size diagnostics. We use continuous observables rather than forcing four labels. Throughout this talk, unresolved means our declared protocol cannot reliably identify the feature; it does not mean a measured zero shift."),
('Control the preparation and the noise','figures/grid_main.png',f'Fixed L6: 192 CNOTs; {s["grid_pass"]}/420 ideal preparations pass',"Every main-grid point uses the same six-layer circuit structure. We optimize energy, compare against exact diagonalization, and freeze the parameters before adding noise. Each actual CNOT is followed by the prescribed depolarizing channel on its target only. We keep the complete density matrix and use no measurement sampling. The three columns share observable color scales. The positive-field grid excludes zero field explicitly. The quality mask remains essential: after bounded repair, nine selected preparations still fail at least one original calibration threshold."),
('Deeper is more accurate ideally, not always after noise','figures/depth_noise.png','Matched points, seeds and budgets; 64 / 128 / 192 CNOTs',"This earlier matched experiment compares the same five points with three depths and the same cold-start budgets. The upper row measures total structure-factor error against exact diagonalization. The lower row measures normalized purity. More layers often improve the ideal result while increasing exposure to noise. The tradeoff varies by point and angle values. We save preparation error and incremental noise separately. Their vectors add, but maximum error norms do not. We do not call accidental error cancellation mitigation, and we do not infer a universal ranking of phase robustness."),
('Compare the chains that actually switch','figures/branch_cases.png',f'{s["switch_intervals"]} intervals audited; {s["old_flags_changed"]} old interval-p flags change',"We found a comparison-identity problem in the previous analysis. A selected curve can switch between two seeds in the same direction, so the best opposite-direction candidate is not necessarily the right control. For each actual interval we now compare both selected chains at the same left endpoint and again at the same right endpoint. All original values remain archived. Unknown and not applicable are separate states. This is a reliability correction to our analysis, not a new physical discovery and not evidence that the density simulator was wrong."),
('High ideal fidelity does not fix noisy output','figures/branch_cases.png','kappa=.3, h=.7: ideal Mx difference 0.0000578; at p=.01: 0.05972',"The right-hand case is particularly useful because both preparations have fidelity above 0.99999 with the exact ground state. They have the same number and order of gates, but different optimized angles. Their ideal transverse magnetizations are nearly identical. At one-percent noise, the difference is about six hundredths. Interleaved noise acts on different intermediate states, so ideal endpoint agreement is not enough to specify the noisy result. We provide both parameter sets, ideal states, all six density matrices, and the gate resource tables so this example can be independently checked."),
('Refine each branch without winner splicing','figures/local_curves.png','Three frozen windows; nested dh=.05 / .025 / .0125; all three p',"For local validation we continue two independent archived sources in each window. We do not choose a new winning branch at every field. The finest grid is computed once, and coarse grids are subsets of the same preparation sequence. That separates resolution effects from fresh random optimization. Both order-feature and magnetization derivatives are examined, with raw-amplitude and prominence thresholds. Failed preparations and possible optimization jumps interrupt derivative support. Some single-feature shifts are visible, but they depend on the branch or lack complementary support. Near-flat noisy curves are not assigned a boundary merely because a mathematical maximum exists."),
('What is supported, and what remains open','figures/local_branch_difference.png','Protocol dependence: supported | universal boundary shift: not established',"Our supported result is that preparation protocol can materially change noisy finite-size diagnostics even when ideal preparations are excellent and gate counts match. Bounded repair improves the grid, and the local tests narrow the claims we can defend. We do not claim a floating phase, thermodynamic critical field, quantum advantage, or common nonzero boundary displacement. The submission includes a fresh-kernel notebook, raw failures, a requirements checklist, and a reproducible archive. A practical lesson is to preserve the full preparation history alongside each observable. A pointwise energy winner is a useful computational choice, but it is not a single continuous experimental protocol. Equally, more precision in the field coordinate cannot repair a missing control comparison. These distinctions explain why we report quality masks and unresolved features alongside the attractive maps, instead of treating a completed scan as a completed physical argument. The remaining team tasks are to add authorship information, review the final scientific wording, and rehearse this presentation against the five-to-seven-minute requirement.")]
notes=[];outline=[];sections=[]
for i,(title,img,subtitle,note) in enumerate(slides,1):
 notes.append(f'## Slide {i}: {title}\n\n{note}\n');outline.append(f'## {i}. {title}\n\n- {subtitle}\n- Figure: {img or "none"}\n- Target: 45–60 seconds\n')
 image=f'<img src="{img}" alt="{html.escape(title)}">' if img else '<div class="hero">Preparation-Protocol Dependence<br>of Noisy ANNNI Phase Diagnostics</div>'
 sections.append(f'<section><div class="count">{i} / 7 · [AUTHOR NAMES] · [TEAM NAME]</div><h1>{html.escape(title)}</h1><p>{html.escape(subtitle)}</p>{image}<details><summary>Speaker notes</summary>{html.escape(note)}</details></section>')
(S/'speaker_notes.md').write_text('# English speaker notes\n\nDraft timing is estimated from word count; actual rehearsal has not been performed.\n\n'+'\n'.join(notes))
(S/'presentation_outline.md').write_text('# 5–7 minute presentation outline\n\nSeven editable slides. Use presentation.html with arrow keys; notes are expandable.\n\n'+'\n'.join(outline))
(S/'presentation.html').write_text('''<!doctype html><meta charset="utf-8"><title>ANNNI presentation</title><style>body{margin:0;background:#0d2033;color:#f3f6fa;font:23px/1.35 system-ui}section{display:none;padding:28px 5vw;min-height:90vh}section.active{display:block}h1{font-size:38px;margin:12px 0}p{color:#9fd6ef}img{display:block;max-height:62vh;max-width:90vw;margin:auto;background:white}details{font-size:17px;margin-top:15px}.count{font-size:15px;color:#b6c6d7}.hero{font-size:52px;padding:15vh 0}nav{position:fixed;bottom:10px;right:15px}button{padding:10px;font-size:18px}@media print{section{display:block;break-after:page}nav,details{display:none}}</style>'''+''.join(sections)+'''<nav><button onclick="show(i-1)">Previous</button> <button onclick="show(i+1)">Next</button></nav><script>let i=0;const s=[...document.querySelectorAll('section')];function show(n){i=Math.max(0,Math.min(s.length-1,n));s.forEach((x,j)=>x.classList.toggle('active',j===i));}document.addEventListener('keydown',e=>{if(e.key==='ArrowRight')show(i+1);if(e.key==='ArrowLeft')show(i-1)});show(0);</script>''')
words=sum(len(r[-1].split()) for r in slides);(S/'presentation_timing.json').write_text(json.dumps({'slides':7,'speaker_note_words':words,'estimated_minutes_at_130_wpm':words/130,'timing_is_estimate':True,'rehearsed':False},indent=2));print('Created seven-slide HTML deck and editable notes:',words,'words')
