import sys,collections
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from annni.stage6_followup import *
C=cfg();cov=read(OUT/'window_completion/coverage.json');summ=read(OUT/'equal_gate_budget/summary.json');paired=read(OUT/'equal_gate_budget/paired.json');stats=read(OUT/'verification/execution_statistics.json');eq=read(OUT/'equal_gate_budget/equality_verification.json');refs=read(OUT/'window_reference.json')
complete=all(r['executed_complete_windows']==6 for r in cov if r['mode']=='equal_shots')
D=dict(run_id=C['run_id'],generated_utc=datetime.now(timezone.utc).isoformat(),window_execution_complete=dict(B3=complete,requested=6,completed=6 if complete else None,new_windows=[0,.3,.5],H6_historical_only=3),reference_resolution_status=dict(resolvable=5,requested=6,unresolved=[.5],scope='Same-N finite-size named response, not thermodynamic boundaries'),frozen_match_status=[r for r in cov if r['budget']==100000],curve_audit_status=dict(scope='Post-Stage6 explanatory flags separate from unchanged frozen score',flags=['endpoint_dominated','competing_peaks','response_amplitude_below_10pct_ED','preparation_observable_failure_near_peak','nearby_branch_noise_effect_not_fully_checked'],position_estimates='delta_h_ED and delta_h_noise only when both required features and curve checks support them; frozen numerical errors separately retained'),equal_CNOT_budget_verified=eq['all_equal'],mitigation_at_equal_budget=[r for r in summ if r['cohort']=='all_B'],remaining_limitations=['Complete execution does not establish reliable phase-boundary recovery.','κ=.5 reference remains unresolved; no zero displacement substituted.','CNOT-shots equality does not equalize shots, single-qubit costs or hardware time.','Physical labels exist only on declared interior subset; colors are not independent phase truth.','32 repeats are measurement repetitions, not new physical coordinates.','Bounded actual-branch controls cannot certify every structure switch harmless.'],execution=stats)
dump(OUT/'decision.json',D)
lines=['# Stage 6 directed followup: B3 windows and equal CNOT-shots','',f"Run `{C['run_id']}`. Started {C['started_utc']}; fixed deadline {C['deadline']}. This is a new directed supplement, not a retroactive preregistered Stage6 experiment.",'','## Scope and execution','',f"All six B3 registered windows complete: **{complete}**. Newly filled κ=0,.3,.5; κ=.45,.55,.8 historical records reused after gate/hash checks. Each has17registered points, p=0,.01,.05, raw/quadratic ZNE/SV,10k/100k total shots and32repeats. H6 remains historical three-window coverage. No VQE, new ansatz, selection or detector retraining.",'',f"Equal-resource cohort: {stats['B_unique_coordinates']} unique coordinates, comprising12 fixed representatives plus complete κ=0,.8 windows, with overlap retained as analysis roles. Coordinates were frozen before new sampling. Both100k×C and300k×C targets executed; zero-CNOT cases are separate fixed-shots controls.",'','## Exact resource definition','',r'G = Σ_settings shots × literal CNOT count. ZNE1/3/5 scales use unchanged nearly equal allocation; choose the maximal integer total not exceeding the target. Raw/SV totalshots equal Σ_fold fold×ZNE_shots, producing exactly equal actual G without identity padding.', '','| Target equivalent shots | ZNE total shots | Raw/SV total shots | Unspent equivalent shots |','|---:|---:|---:|---:|']
for b in C['equal_gate_base_budgets']:
 z,e=equal_gate_shots(b);lines.append(f'| {b} | {z} | {e} | {b-e} |')
lines+=['','SV has30local settings; raw has2; ZNE has6. Extra local measurement gates and all settings are charged separately. Equality of G is not equality of all costs. The full C/SF/Mx vector retains17equal-weight components, including correlated Fourier-related components, to preserve the historical MSE definition. Group errors are separately reported; no new reweighting.','', '## Same-coordinate estimator results','', '| Protocol | Budget | p | Estimator | Coordinates | MSE ED | MSE own clean | Total G,32 repeats |','|---|---:|---:|---|---:|---:|---:|---:|']
for r in summ:
 if r['cohort']=='all_B':lines.append(f"| {r['mode']} | {r['budget']} | {r['p']} | {r['method']} | {r['points']} | {r['MSE_ED_mean']:.8g} | {r['MSE_own_clean']:.8g} | {r['CNOT_shots_all32']} |")
lines+=['','### Paired changes versus same-budget raw','', '| Protocol | Budget | p | Estimator | Mean MSE change | Improved / worse / equal coordinates |','|---|---:|---:|---|---:|---|']
for r in paired:
 if r['cohort']=='all_B':lines.append(f"| {r['mode']} | {r['budget']} | {r['p']} | {r['method']} | {r['mean_MSE_change']:.8g} | {r['improved']} / {r['worsened']} / {r['equal']} |")
lines+=['','[Full point metrics](equal_gate_budget/point_metrics.csv) include C/SF/Mx errors, physical-label eligibility, D3correct/wrong/reject outputs for every repeat, bias/sampling/cross-term decomposition and unclipped estimates. [Resource audit](equal_gate_budget/resource_audit.csv) lists every allocation. [Window costs](window_completion/window_costs.csv) sum all17points and all32repeats, separately for each p.','', '## Frozen window scores versus curve audit','', '| Protocol | Budget | p | Estimator | Executed/requested | Reference-resolvable | Matched window equivalents | Matches with issues | Matches without issues |','|---|---:|---:|---|---|---:|---:|---:|---:|']
for r in cov:
 if r['budget']==100000:lines.append(f"| {r['mode']} | {r['budget']} | {r['p']} | {r['method']} | {r['executed_complete_windows']}/{r['requested_windows']} | {r['reference_resolvable_windows']} | {r['frozen_matching_window_equivalents']:.5g} | {r['matched_problem_window_equivalents']:.5g} | {r['quality_supported_match_window_equivalents']:.5g} |")
lines+=['','Each window is averaged over32complete-curve repetitions before summing window equivalents. These are not thousands of independent boundaries. A frozen interior-peak match remains a match even with a larger endpoint response; the separate issue flags prevent claiming it as reliable physical recovery. All peak lists and failed/unresolved repeats remain in [matches.json](window_completion/matches.json).','', 'κ=.5 is still reference_unresolved. Its curves were executed, but qualified displacements are null. The observational audit does not move/recenter windows or change frozen thresholds. Curves retain all preparation failures; no interpolation fills them. Signed δh_ED includes preparation/diagnostic differences; Δh_noise uses the same circuit protocol at p0 and is withheld where either required feature/curve is unsupported.','', '[Historical actual branch comparisons](branch_switches_historical.json) preserve both switched branches at the same coordinate. [New bounded branch controls](window_completion/branch_controls.json) check selected critical switches under noise; untested switches are not called harmless.','', '## Figures','']
for f,title in [('six_window_orders.png','Order curves'),('six_window_responses.png','Full response curves with all local peaks'),('coverage_and_issues.png','Execution, matching and curve issues'),('equal_resource_MSE_cost.png','Equal shots versus equal CNOT-shots'),('equal_resource_window_features.png','All equal-resource window repeats and failures')]:lines+= [f'### {title}','',f'![{title}](figures/{f})','']
lines+=['## Evidence and reproduction','',f"Unique new measurement records: {stats['new_measurement_records']}; reused records: {stats['reused_measurement_records']}. New joint multinomial draws: {stats['new_joint_multinomial_draws']}; represented new simulated shots: {stats['new_simulated_shots']}. These are classical samples of saved quantum-model probabilities, not QPU executions. New density records: {stats['new_density_records']}; reused probability records: {stats['reused_probability_records']}. Summed newly simulated density time: {stats['density_seconds']:.2f}s. Peak process RSS: {max(stats['peak_rss_bytes'],stats.get('analysis_process_peak_rss_bytes',0))/1024**3:.3f}GiB.",'','Old and new counts are never obtained by scaling plotted curves. New gate-budget counts use independent explicitly keyed random streams; same-setting observables retain covariance through whole-bitstring counts. Historical equal-shots common streams remain tagged; paired statistics group physical coordinates and never count shared estimator analyses as new execution.','', 'Install the scientific or portable environment using [the reproduction instructions](../../docs/REPRODUCE.md), then run these commands from the repository root:','','```sh','bash scripts/stage6_followup.sh --verify','bash scripts/stage6_followup.sh --redraw','```','','The default interpreter is `.venv/bin/python`. For another installed environment, prefix either command with `ANNNI_PYTHON=/path/to/python`.','','`--verify` runs the release V1 check: it verifies the package hashes, reconstructs all 2,718 active records from saved joint counts, and checks coordinates, gate tables and equal CNOT-shot budgets. Its receipt is written to `build/stage6_followup/verification/verify_data.json`. This is a saved-data check; physical circuit checks and environment-specific random replay have separate commands in the reproduction instructions.','','`--redraw` recreates the five figures above from bundled numerical tables and curves, writing them to `build/stage6_followup/figures/`. The published images remain in `results/stage6_followup_v1/figures/`. These commands leave the archived data and published files unchanged and require no optional Release assets.','','The original research run has ended. Its historical resume procedures and deadlines do not apply to this publication entry point. The executed notebook separates saved experiments from representative count reconstruction; the commands above verify and redraw the completed followup.']
(OUT/'REPORT.md').write_text('\n'.join(lines)+'\n');print('Report and decision written')
with (OUT/'REPORT.md').open('a') as f:
 f.write('\n## Followup implementation provenance\n\nThe first A attempt stopped when a same-coordinate core record had a different literal B3 gate table from the registered window. The assertion prevented consuming it. A versioned lookup fix rejects that source and searches compatible records; the catalog retains both core and window fingerprints. Valid earlier draws remain archived and costed but are not pooled with final draws after the sampler fingerprint changed. This is an execution/cache correction, not a change in B3 or mitigation. See verification/A_attempt1_failure.log and verification/cache_catalog_enrichment.json.\n\nBefore B began, the original control at(.7,1.5), which lacked an independent interior label, was replaced by the declared antiphase interior(.8,.1). The original config, time and unchanged deadline are retained in verification/control_cohort_amendment.json. No equal-resource outcomes had been generated.\n\nFinal completion inventories: [windows](window_inventory_completed.csv), [resource experiments](resource_experiment_inventory_completed.csv), [old-versus-new coverage](window_completion/old_vs_followup_coverage.csv). Initial inventories remain separate snapshots.\n')
 f.write('\n## Actual switched-branch noise controls\n\nThese compare the two actual switched branches at one identical coordinate. They are not alternative opposite-direction surrogates, error bars or proof that every switch is harmless.\n\n| κ | Switch interval | Same coordinate h | Max C difference p0 | p=.01 | p=.05 |\n|---:|---|---:|---:|---:|---:|\n')
 for r in read(OUT/'window_completion/branch_controls.json'):
  values={x['p']:x['max_C_difference'] for x in r['differences']}
  f.write(f"| {r['kappa']} | [{r['left_h']},{r['right_h']}] | {r['same_coordinate_h']} | {values[0]:.6g} | {values[.01]:.6g} | {values[.05]:.6g} |\n")
# Source-derived interpretation, written only after all fixed cohorts execute.
def result(mode,b,p,m):return next(r for r in summ if (r['cohort'],r['mode'],r['budget'],r['p'],r['method'])==('all_B',mode,b,p,m))
conclusions=[]
for p in [.01,.05]:
 raw=result('equal_gate',100000,p,'raw');zne=result('equal_gate',100000,p,'zne_quadratic');sv=result('equal_gate',100000,p,'sv');pair=next(r for r in paired if (r['cohort'],r['mode'],r['budget'],r['p'],r['method'])==('all_B','equal_gate',100000,p,'zne_quadratic'))
 conclusions.append(dict(p=p,raw_MSE=raw['MSE_ED_mean'],ZNE_MSE=zne['MSE_ED_mean'],SV_MSE=sv['MSE_ED_mean'],ZNE_relative_mean_MSE_reduction=1-zne['MSE_ED_mean']/raw['MSE_ED_mean'],ZNE_improved_points=pair['improved'],coordinates=pair['coordinates'],raw_bias_squared=raw['bias_squared'],raw_sampling_MSE=raw['sampling_MSE'],ZNE_bias_squared=zne['bias_squared'],ZNE_sampling_MSE=zne['sampling_MSE']))
D['source_derived_conclusions']=conclusions;D['noiseless_mitigation']=dict(raw_MSE=result('equal_gate',100000,0,'raw')['MSE_ED_mean'],ZNE_MSE=result('equal_gate',100000,0,'zne_quadratic')['MSE_ED_mean'],scope='Noiseless exact estimator bias unchanged; extra sampling error raises MSE.');dump(OUT/'decision.json',D)
lead=['## Actual findings','', 'The execution gap is closed, but reliable boundary recovery is not established. New κ=0 and.3 noisy curves contain structure-sensitive peaks; κ=.5 remains reference-unresolved. At100k equal shots, p=.05 raw gives2.96875/5 matched window equivalents and quadratic ZNE2.875/5; these are32-repeat-normalized values, not integer counts of independently validated transitions. Raw matches include endpoint-dominated κ=.45/.55 curves.','']
for r in conclusions:lead.append(f"At equal CNOT-shots target100k×C and p={r['p']}, quadratic ZNE reduces mean ED-target MSE from{r['raw_MSE']:.8g} to{r['ZNE_MSE']:.8g} ({100*r['ZNE_relative_mean_MSE_reduction']:.2f}% reduction), improving{r['ZNE_improved_points']}/{r['coordinates']} tested coordinates. SV gives{r['SV_MSE']:.8g}. Raw exact bias squared is{r['raw_bias_squared']:.8g}, compared with sampling MSE{r['raw_sampling_MSE']:.3g}; ZNE lowers exact bias to{r['ZNE_bias_squared']:.8g} while increasing sampling MSE to{r['ZNE_sampling_MSE']:.3g}. Thus the net gain is primarily bias reduction, not extra shots or lower variance. Sampling MSE includes finite-sample bias; point tables also report variance and the exact cross-term decomposition.")
lead+=['','At p0, ZNE worsens MSE on45/45points at the main equal-G budget. At p=.05, SV improves40/45 and worsens5/45. More raw shots at the high budget barely change noise-dominated MSE. The restricted equal-resource κ=0/.8 window pair shows that lower observable MSE is not better feature localization: at p=.01, raw matches1/2 window equivalents while ZNE matches.59375/2; at p=.05, values are1/2 and.8125/2. These numerically matched noisy curves retain audit issues.','', 'Only6/45coordinates have independent interior labels. At p=.05/main equal-G, D3 gives raw4/6 and ZNE4.25/6 correct coordinate-equivalents averaged over32repeats; this small local change is not proof of whole-phase classification recovery or a statistical significance claim.','']
p=OUT/'REPORT.md';text=p.read_text();first,rest=text.split('\n',1);p.write_text(first+'\n\n'+'\n'.join(lead)+rest)

with (OUT/'REPORT.md').open('a') as f:
 f.write(f"\nThe final analysis contains{stats['active_analysis_measurement_records']}measurement records:{stats['active_new_measurement_records']}new records and{stats['active_reused_measurement_records']}historical reused records. Each has32repeats. An additional{stats['retained_prior_attempt_measurement_records']}valid first-attempt records are retained, excluded from final inference, and included in the actual execution-cost totals above. The{stats['active_unique_coordinates']}active unique coordinates are102window coordinates plus8additional representatives; the45-point B cohort overlaps the A windows. At overlapping representative/window coordinates the intake consistently keeps the registered window's frozen B3 circuit for both roles; this was determined before B outcomes, not selected by mitigation performance.\n")
