"""Editable Stage5 deck, OfficeCLI, figures from executed tables."""
import json,subprocess
from pathlib import Path
R=Path(__file__).resolve().parents[1];S=R/'results/stage5_v1/submission';file=S/'presentation.pptx'
slides=[
('Reliable selection and noisy diagnosis','Q-SITE 2026 Scientific Track | Local simulation study','pipeline.png',"This project asks whether correcting near-degenerate circuit selection actually improves noisy physical diagnosis. We keep the periodic ANNNI Hamiltonian, the preparation tolerances and the prescribed target-only noise after every CNOT. The old grid and old held-out coordinates are now development data. We freeze twenty-four new validation coordinates and seventy-two new test coordinates, plus a separate twelve-spin test. Every result shown comes from saved executed experiments. Ideal-state access, noisy execution, finite-shot estimation and larger open-chain physics are separated. We do not load exact ground states into the preparation circuit or claim a quantum advantage."),
('Coverage and preparation cost','New test: 60/72 to 62/72; energy-only S1 also reaches 62','selection.png',"The old resource window sometimes picks an inaccurate low-energy state even though a good candidate exists. We reconstruct all old checkpoints and compare selectors on exactly the same candidates. S2 uses parity and zero-momentum weights, then a tighter energy window. Its thresholds are frozen before testing. A definite nonzero momentum can have translation magnitude one, and a same-sector excited state can have zero variance, so neither diagnostic certifies ground-state fidelity. The new selector passes two additional test coordinates, but energy-only selection achieves the same count. Most old failures have no passing candidate. Median CNOT cost rises from ninety-six to one hundred twenty-eight."),
('Gate-noise tradeoff','B5 raw noise is worse than the shorter B3 baseline','noise_comparison.png',"The full four-hundred-twenty-coordinate comparison includes all failures. At one percent noise, average maximum correlation error is about zero point one four three for B3 and zero point one eight two for B5. At five percent it is about zero point three six seven and zero point four one two. B5 still improves over the older deep HVA, but that is not enough to justify replacing B3. Hard symmetry filtering can also retain a much higher-energy candidate at difficult points. We keep those negative outcomes and unsuccessful bounded retries. Candidate generation, selection and execution resources are reported separately rather than merged into a single success percentage."),
('Correct identification and rejection','At p=.05, B3 + D3 identifies more anchors than B5 + ZNE','strong_noise_detectors.png',"Five arms are evaluated at the same coordinates: B0 raw, B3 raw, B5 raw, B5 with zero-noise extrapolation, and B5 with parity verification. Each receives ten thousand or one hundred thousand total shots, with thirty-two independent repetitions. Those budgets are shared across settings and folding scales. Joint bitstrings preserve covariance. At five percent noise, D1 with B5 extrapolation identifies sixty-four of three-hundred-eighty-four anchor trials, while D3 with old B3 raw identifies one-hundred-ninety-two. Both have no wrong accepted trials in this small anchor set. The chart separates correct, wrong-accepted and rejected outcomes on a fixed set of independently motivated physical anchors. Transition regions have no invented exact phase labels. Their agreement with an ED-based diagnostic is called diagnostic agreement, not classification accuracy. The same frozen D1 and D3 rules receive observables only."),
('Mitigation at a fixed shot budget','ZNE chosen on validation; preparation bias remains separate','mitigation.png',"Zero-noise extrapolation folds every CNOT by one, three and five, including reference preparation, then applies a fixed linear intercept. Neither exact data nor zero-noise results enter that noisy fit. Parity verification uses signed observable-parity products and thirty measurement settings for eight spins. It cannot correct the momentum sector. Raw estimation has two settings and extrapolation six. Gate-weighted measurement costs therefore differ even at equal shots. The target of mitigation is the same circuit at zero noise; residual preparation error against ED is separate. Unphysical estimates are retained rather than clipped. Low rejection by itself does not establish reliable feature recovery."),
('Twelve-spin resource limits','New N12 test: 11/24 to 17/24 at 128 versus 192 CNOT caps','n12_noise.png',"We reuse all old twelve-spin candidates before running a paired higher-budget experiment on sixty old and twenty-four new coordinates. The same seeds and reference choices are used, and the deterministic search prefixes are shared. This is not an additional independent restart. The comparison distinguishes a selector choosing badly from a candidate pool lacking an accurate circuit. Exact density matrices then test twelve predeclared coordinates at all three noise levels, including failed preparations. Six also receive a finite-shot raw and parity-verification comparison, now with sixty-eight settings. The new test rises from eleven to seventeen of twenty-four passes. Extra gates and longer classical search both contribute; All twelve paired raw-noise cases worsen at both nonzero noise levels."),
('Independent floating-phase evidence','Three centers gain support; N160 retains window sensitivity','floating_size.png',"The tensor-network analysis is independent physics validation on open chains. We add one-hundred-twenty-eight sites, two bond dimensions and two initial states at each of three old centers, plus neighboring fields at ninety-six and one-hundred-twenty-eight sites. Signed oscillatory power and exponential models have equal parameter counts. We test extrapolation to a contiguous block of distances, two fit windows, connected correlations and bond convergence. Entropy uses the open-chain coefficient with central charge fitted freely. A corrected fit is explicitly exploratory sensitivity. All three centers gain support. At the third center, N160 gives c from1.055 to1.083. Composite evidence aggregation was specified after computation began, so it is not a fully preregistered phase test. Neither bond convergence nor a few supported discrete points proves a continuous thermodynamic floating phase."),
('Integrated results and deployment decision','Verified pipeline; no unconditional B5 replacement or strong-noise map','dynamics.png',"Independent dynamics adds seventy-two configurations at six new quench coordinates and recomputes two old sequences. Smaller time steps reduce ideal Trotter error but double the CNOT count and increase noisy total error. This reinforces the central lesson: improving one noiseless component does not ensure a better end-to-end result. The submission retains preparation failures, branch sensitivity, measurement uncertainty and finite-size limitations. It includes raw candidates, literal gates, joint counts, tensor-network checkpoints, an executed notebook and clean-extraction verification. The verified methods support qualified observable comparisons, but the current results do not support an unconditional B5 replacement or a recovered five-percent-noise phase map.")]
(S/'presentation_design.json').write_text(json.dumps(dict(motif='Consistent numbered project footer, white background, dark blue type, quantitative data figures',title_grammar='topic noun phrases',slide_titles=[s[0] for s in slides],type_sizes=dict(title=36,subtitle=20,footer=10),editable='Titles, subtitles, footer and speaker notes are native editable PowerPoint elements; scientific plots are embedded images with separate editable Python source and raw data.'),indent=2))
(S/'speaker_notes.md').write_text('\n\n'.join(f'## {i+1}. {a}\n\n{d}' for i,(a,b,c,d) in enumerate(slides)))
(S/'presentation_outline.json').write_text(json.dumps(slides,indent=2));words=sum(len(s[3].split()) for s in slides);(S/'presentation_timing.json').write_text(json.dumps(dict(words=words,minutes_at_130wpm=words/130,measured_rehearsal=False),indent=2))
def cmd(*args):
 r=subprocess.run(['officecli',*map(str,args)],capture_output=True,text=True,check=True)
 if 'UNSUPPORTED' in r.stdout+r.stderr:raise RuntimeError(r.stdout+r.stderr)
 return r.stdout
if file.exists():raise SystemExit('Presentation already exists; preserve and explicitly version a rebuild')
cmd('create',file)
for i,(title,subtitle,figure,notes) in enumerate(slides,1):
 path=f'/slide[{i}]';cmd('add',file,'/','--type','slide','--prop','layout=blank','--prop','background=FFFFFF');cmd('get',file,path)
 def shape(text,x,y,w,h,size,bold=False,color='263238'):
  return cmd('add',file,path,'--type','shape','--prop',f'text={text}','--prop',f'x={x}cm','--prop',f'y={y}cm','--prop',f'width={w}cm','--prop',f'height={h}cm','--prop',f'size={size}','--prop','font=Arial','--prop',f'bold={str(bold).lower()}','--prop',f'color={color}','--prop','fill=none','--prop','line=none')
 shape(title,1.3,1.3,31,2,36,True);shape(subtitle,1.3,3.4,31,1.2,20)
 # Image aspect ratio retained; capped height leaves readable footer.
 from PIL import Image
 im=Image.open(S/'figures'/figure);iw,ih=im.size;scale=min(30/iw,10.5/ih);w,h=iw*scale,ih*scale
 cmd('add',file,path,'--type','picture','--prop',f'src={S/"figures"/figure}','--prop',f'x={(33.867-w)/2}cm','--prop','y=5.3cm','--prop',f'width={w}cm','--prop',f'height={h}cm','--prop',f'alt={title}: executed numerical data');cmd('get',file,path)
 shape(f'ANNNI Stage 5 | 22 September 2026 | {i}/8',1.3,17.0,31,.7,10,color='616161')
 cmd('add',file,path,'--type','notes','--prop',f'text={notes}')
cmd('save',file)
(S/'presentation_schema.log').write_text(cmd('validate',file));(S/'presentation_issues.log').write_text(cmd('view',file,'issues'));(S/'presentation_text.log').write_text(cmd('view',file,'text'));print(file,words,'words')
