import json,hashlib,platform,os,shutil
from pathlib import Path
from datetime import datetime,timezone,timedelta
R=Path(__file__).resolve().parents[1];O=R/'results/stage6_v1';O.mkdir(exist_ok=True)
for s in ['reference_atlas','failure_mechanisms','domain_wall_candidates','confirmation','noise_diagnosability','end_to_end','n8_maps','n12_transfer','floating_boundary_scan','verification','report']: (O/s).mkdir(exist_ok=True)
p=O/'experiment_plan.json'
if p.exists(): raise SystemExit('Existing Stage6 plan retained')
now=datetime.now(timezone.utc)
validation=[[k,h] for k in [.407,.427,.577,.597] for h in [.018,.058,.118]]+[[k,h] for k in [.715,.915] for h in [.29,.43,.57]]+[[k,h] for k in [.115,.315,.815] for h in [.165,1.715]]
confirmation=[dict(kappa=k,h=h,region='low_field') for k in [.443,.459,.4757,.491,.507,.523,.539,.555] for h in [.013,.028,.044,.068,.093,.138]]+[dict(kappa=k,h=h,region='antiphase_band') for k in [.663,.763,.863,.963] for h in [.235,.305,.375,.445,.515,.585]]+[dict(kappa=k,h=h,region='interior') for k in [.083,.183,.283,.383,.683,.883] for h in [.085,.175,1.675,1.875]]
plan=dict(run_id='stage6_'+now.strftime('%Y%m%dT%H%M%SZ'),started_utc=now.isoformat(),deadline=(now+timedelta(hours=12)).isoformat(),wall_budget_seconds=43200,python=platform.python_version(),budget_fraction=dict(reference=.20,candidates=.35,noise=.20,mps=.20,report=.05),resources=dict(max_heavy_processes=2,working_memory_cap_bytes=6*1024**3,blas_threads_requested=1,cpus=os.cpu_count(),disk_free=shutil.disk_usage(R).free),validation=validation,confirmation=confirmation,seeds=dict(development=[101,211,307],validation=[419],confirmation=[631],stability=[743]),thresholds=dict(delta_e=.001,epsilon_c=.02,epsilon_sf=.02,epsilon_mx=.02,fidelity=.99),optimization=dict(maxiter=400,ftol=1e-12,gtol=1e-7,maxls=30,gradient_stop=1e-8,selection_energy_tolerance_per_site=1e-6),search=dict(top_k=4,probe_maxiter=35,budgets_n8=[64,96,128],budgets_n12=[128,192],refs_physical=['plus','ghz','antiphase'],refs_wall=['uniform','empty','alternating']),atlas=dict(kappa_n8=[0,.1,.2,.3,.4,.45,.475,.5,.525,.55,.6,.7,.8,.9,1],kappa_large=[0,.3,.45,.5,.55,.8],low_kappa=[round(.4+.025*i,3) for i in range(9)],low_h=[.01,.02,.035,.05,.075,.10,.125,.15,.20,.25,.30,.35],peak_refine_halfwidth=.05,refine_step=.0125,diagnostics=['dmx_dh','minus_dm0_dh','minus_dmap_dh','chi_f','binder','sector_gap']),mps=dict(kappa=.8,coarse_h=[round(.1+.05*i,3) for i in range(15)],coarse_n=64,coarse_chi=128,max_sweeps=32,midpoint_halfwidth=2,max_r_fraction=1/3,fit_windows=[[2,.25],[4,1/3]],high_extension=[.9,1.0,1.2,1.5],low_extension=[.05,.025],refinement_chi=[128,256],refinement_n=[96,128],initials=['plus','antiphase'],rule='Locate two strongest distinct changes in central correlation tail, q and entropy/response; if no two, preserve unresolved and sample both endpoint neighborhoods and central crossover. Never select by c closest to1.',max_refinement_points=9),measurement=dict(p=[0,.01,.05],budgets=[10000,100000],repeats=32,seed=62026),split_limit='Spatial kappa blocks separate new low-field validation and confirmation; old development grid spans domain, so confirmation measures new-coordinate interpolation, not unseen-phase extrapolation.',physics='PBC circuits; OBC MPS; wire0 MSB; full Hamiltonian; all literal CNOTs target-depolarized; direct NN/NNN connectivity',historical_stage5='results/stage5_v1',new_stage6=True)
plan['coordinate_hash']=hashlib.sha256(json.dumps(dict(validation=validation,confirmation=confirmation),sort_keys=True).encode()).hexdigest()
p.write_text(json.dumps(plan,indent=2));(R/'configs/stage6_v1.json').write_text(p.read_text())
# Reuse independently recorded protected hashes, without rehashing every old archive now.
old=json.loads((R/'deliverables/PACKAGE_MANIFEST_STAGE5.json').read_text())['files'];protected={k:v['sha256'] for k,v in old.items() if k.startswith(('results/baseline/','results/stage3','results/stage4','results/stage5','upstream/'))};(O/'verification/protected_inputs.json').write_text(json.dumps(protected,indent=2))
(O/'verification/input_mapping.json').write_text(json.dumps(dict(baseline='results/baseline',B3='results/stage4_upgrade_v1',stage5='results/stage5_v1',existing_tests='80 passed in9.88s newly_executed before modifications',protected_manifest_source='deliverables/PACKAGE_MANIFEST_STAGE5.json',protection_scope='Scientific old records read-only; no claim of freshly rehashing all files at start'),indent=2));print(plan['run_id'],plan['deadline'])
