"""Three-page submission summary, from audited numerical tables."""
import json
from pathlib import Path
from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,Image,PageBreak,Table,TableStyle
from reportlab.lib.styles import getSampleStyleSheet,ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
R=Path(__file__).resolve().parents[1];O=R/'results/stage5_v1';S=O/'submission';st=json.loads((S/'statistics.json').read_text());n12=json.loads((O/'n12_scaling/analysis.json').read_text());fl=json.loads((O/'floating_validation/evidence_update.json').read_text());styles=getSampleStyleSheet();styles.add(ParagraphStyle(name='BodySmall',fontName='Helvetica',fontSize=9,leading=12,spaceAfter=7));styles.add(ParagraphStyle(name='PaperTitle',fontName='Helvetica-Bold',fontSize=20,leading=23,spaceAfter=10));styles['Heading2'].fontSize=12;styles['Heading2'].leading=15;story=[]
def para(s,style='BodySmall'):story.append(Paragraph(s,styles[style]))
def figure(name,width=490):
 from PIL import Image as PILImage
 p=S/'figures'/name;w,h=PILImage.open(p).size;story.append(Image(str(p),width=width,height=width*h/w));story.append(Spacer(1,6))
def header(title):para(title,'Heading2')
para('Circuit selection and noisy<br/>phase-feature diagnosis','PaperTitle');para('Q-SITE 2026 Quantum Coalition - Scientific Track | Stage 5 | Executed local simulations')
header('Question and controlled protocol')
para('We test whether fixing near-degenerate candidate selection improves the complete chain from circuit preparation to noisy physical features. The periodic Pauli ANNNI model uses N=8/12, J1=1 and h&gt;0. Every literal CNOT, including reference preparation and folding, receives target-only depolarization at p=0, .01 or .05. All C(r), discrete structure factors and transverse magnetization are retained. The original energy, observable and fidelity tolerances remain unchanged.')
header('Frozen, nonoracle selector')
para('S0 uses the old energy/resource rule. S1 minimizes energy. S2 requires parity weight at least .999999 and zero-momentum weight at least .99, then a 1e-6 per-spin energy window. Thresholds are frozen on 24 new validation coordinates before 72 new test coordinates are unsealed. S2 uses exact ideal-state access for classical circuit design; no free projection or hardware implementation of translation measurement is claimed. Counterexamples verify that parity, definite momentum and small variance are not ground-state certificates.')
figure('selection.png')
para('On the new test, S0 passes 60/72 and both S1 and S2/B5 pass 62/72. On 420 old descriptive coordinates, 385 becomes 388; the candidate pool contains only 388 qualified solutions. Most failures are therefore not repaired by selection. Median CNOTs increase from 96 to 128. Hard symmetry filtering can also retain a substantially higher-energy state at difficult points. These failures remain in every denominator.')
para('Original 420/48 coordinates are development/descriptive data. Three reference starts at seed 11 are distinct reference experiments, not three independent random-seed replications. The N8 cap remains 128 CNOT; bounded retries add classical search without adding gates.')
story.append(PageBreak());para('Matched end-to-end outcomes','PaperTitle')
para(f"Five arms share {st['available_core_points']} fixed core coordinates: B0 raw, B3 raw, B5 raw, B5 ZNE and B5 SV. Each p uses the same ideal parameters. Total budgets are 10,000 and 100,000 shots, each with 32 independent whole-bitstring sampling repetitions; covariance and gate-weighted costs are saved. Common local windows are evaluated at .025 and .0125 steps with actual structure-switch and fixed-structure controls.")
figure('strong_noise_detectors.png')
para('At p=.05, D1 with B5 ZNE gives64/384 correct anchor trials versus0 with B5 raw, but frozen D3 with the older B3 raw gives192/384 correct versus64 for B5. All these cases have0 wrong accepted trials; unrecognized trials remain rejected. The benefit is detector-specific, not superiority over the best old baseline. The displayed labels are evaluated only on frozen, independently motivated physical anchors. Unlabelled transition regions use observable reconstruction and agreement with ED diagnostics, not invented classification truth. Correct, wrong-accepted and rejected outcomes use a fixed denominator. D1/D3 receive observables only. D2 uses full simulator density matrices and is outside the local measurement budget.')
header('Clean coverage and gate noise pull in different directions')
para('Full-grid mean maximum correlation error at p=.01 is B0/B3/B5=.2638/.1432/.1821; at p=.05 it is .4454/.3666/.4117. B5 improves over the old deep HVA but is worse than B3. ZNE is chosen using only the 24 validation coordinates and then extended to the full descriptive map. No strong-noise full-phase recovery or universal boundary displacement is claimed.')
para('ZNE folds every CNOT by 1/3/5 and fits a fixed linear intercept without p=0 or ED. SV uses the signed (O+OP)/(1+P), requiring 30 local settings at N8 and 68 at N12; it does not fix momentum. Raw uses two settings and ZNE six. All consume the same total shots. Unphysical estimates are retained rather than clipped; preparation bias is separated from the noise increment.')
header('Twelve-spin scaling')
para('On the 60 old coordinates, the 128-CNOT S0/S1/S2 rules pass40/40/41 points; S2 at192 CNOTs passes52. On the24 new test coordinates, these counts are10/9/11 and17. Bounded same-gate retries add no joint passes. Optimizer termination and physics acceptance remain separate in the full tables.')
para('The 128/192-cap runs share deterministic seeds and optimization prefixes. Paired three-p exact-density execution includes failed preparations at 12 fixed coordinates; six also receive raw/SV finite-shot estimation. Extra quantum gates and extra classical search are both charged. This is a controlled resource contrast, not a full N12 noisy phase map.')
if n12['noise_paired'] and all(r['total']==12 for r in n12['noise_paired']):
 r=next(r for r in n12['noise_paired'] if r['p']==.05 and r['before']=='S2_128' and r['after']=='S2_192')
 para(f"At p=.05, increasing the cap changes mean maximum correlation error by {r['mean_difference']:+.4f}; {round(12*r['improved_fraction'])}/12 paired coordinates improve. This measured noisy contrast includes both extra gates and longer adaptive optimization.")
story.append(PageBreak());para('Independent physical validation','PaperTitle');figure('floating.png',470)
para('New open-chain TeNPy calculations test three centers at N=128, chi=128/256 and two initial states, plus six neighboring h values at N=96/128 and Ising/gapped controls. Signed oscillatory power and exponential models have equal parameter counts. Two fit windows, raw/connected correlations, held-out contiguous distance blocks and entropy/bond/size sensitivity are checked separately. No ordinary least-squares uncertainty is promoted to thermodynamic significance.')
para('; '.join(f"({r['kappa']}, {r['h']}): {r['new_grade']}, c={', '.join(f'{x:.3f}' for x in r['entropy_c'])}" for r in fl['rows'])+'. Numeric settings were frozen, but the all-block composite aggregation was specified after jobs began and is disclosed as evidence review. These grades concern discrete tested OBC points. Four of39 main runs miss the configured sweep stopping tolerances; this is reported separately from bond stability. The exploratory corrected-entropy regression does not determine the grade; finite size remains distinct from bond convergence. The optional N160 check at (1,.7) gives c=1.083/1.055 across windows, so the earlier elevated coefficient weakens but remains window-sensitive. Large-system labels are not transferred to small periodic noisy states.')
header('Dynamics and final decision')
para('Seventy-two new quench configurations test six coordinates, two fixed product initial states, two time steps and three noise levels; two old sequences are recomputed. Halving dt improves ideal Trotter error but doubles CNOTs from 640 to 1280 and increases noisy total error. These finite-time diagnostics are not phase-classification certificates.')
para('<b>Decision:</b> use the verified pipeline for masked, region-qualified comparisons. Do not unconditionally replace B3 by B5, infer recovered p=.05 phases from lower rejection, or claim precise thermodynamic boundaries. The reproducible package retains candidate histories, selected parameters, literal gates, joint counts, MPS checkpoints, tests and an executed notebook.')
para('<b>Primary sources:</b> Boyd, Stanford EE363 Lecture 17 (2008-09), pp5-7, Perron-Frobenius; Tang et al., PRX Quantum 2, 020310 (2021); Cea et al., arXiv:2402.11022; Beccaria et al., cond-mat/0702676; Bonet-Monroig et al., PRA 98, 062339 (2018). Official TeNPy 1.1.1 / PennyLane 0.44.1 / Mitiq references and access provenance are included. New conclusions are our simulations. Verify: bash scripts/reproduce_stage5.sh --verify.')
def footer(c,doc):c.setFont('Helvetica',8);c.setFillColor(colors.HexColor('#52616b'));c.drawString(42,24,'ANNNI Stage 5 | All failures retained | Simulation-assisted design');c.drawRightString(553,24,str(doc.page))
SimpleDocTemplate(str(S/'report.pdf'),pagesize=(595,842),rightMargin=42,leftMargin=42,topMargin=35,bottomMargin=40).build(story,onFirstPage=footer,onLaterPages=footer)
from pypdf import PdfReader
n=len(PdfReader(S/'report.pdf').pages);assert n==3,n;print('PDF pages:',n)
