"""Save completed checkpoints and precise remaining entry points, without starting work."""
import json,sys
from pathlib import Path
from datetime import datetime,timezone
R=Path(__file__).resolve().parents[1];O=R/'results/stage5_v1';plan=json.loads((O/'experiment_plan.json').read_text())
jobs=[('test72','selector_benchmark/test/index.json',72,'.venv/bin/python scripts/run_stage5_candidates.py --task test'),('n12test24','selector_benchmark/n12test/index.json',24,'.venv/bin/python scripts/run_stage5_candidates.py --task n12test'),('n12budget84','selector_benchmark/n12_192/index.json',84,'.venv/bin/python scripts/run_stage5_candidates.py --task n12_192'),('windows43','selector_benchmark/windows/index.json',43,'.venv/bin/python scripts/run_stage5_candidates.py --task windows'),('core94','end_to_end/core_index.json',94,'.venv/bin/python scripts/run_stage5_e2e.py --task core'),('validation144','end_to_end/validation_index.json',144,None),('MPS39','floating_validation/index.json',39,'.venv-tn/bin/python scripts/run_stage5_floating.py'),('map420','n8_maps/noise_index.json',420,'.venv/bin/python scripts/run_stage5_map_noise.py'),('fullZNE420','end_to_end/full_best_index.json',420,'.venv/bin/python scripts/run_stage5_e2e_full.py --task full_best'),('N12noise12','n12_scaling/noise_index.json',12,'.venv/bin/python scripts/run_stage5_n12_noise.py'),('N12mitigation6','end_to_end/n12_index.json',6,'.venv/bin/python scripts/run_stage5_e2e_n12.py --task n12'),('dynamics72','dynamics_validation/index.json',72,'.venv/bin/python scripts/run_stage5_dynamics.py')]
rows={name:len(json.loads((O/path).read_text())) if (O/path).exists() else 0 for name,path,count,cmd in jobs};now=datetime.now(timezone.utc)
record=dict(timestamp=now.isoformat(),deadline=plan['deadline'],elapsed_seconds=(now-datetime.fromisoformat(plan.get('started_utc',plan.get('started')))).total_seconds(),completed=rows,next_commands=[cmd for name,path,count,cmd in jobs if rows[name]<count and cmd],note='Saved completed checkpoints only. Commands require unchanged fingerprints and deadline guards. Check existing active processes before resuming to avoid duplicate jobs. This status script does not start background jobs. After numerical completion: analyses, export, tests and packaging gates still apply.')
with (O/'verification/progress.jsonl').open('a') as f:f.write(json.dumps(record)+'\n')
print(json.dumps(record,indent=2))
