import json
from pathlib import Path
R=Path(__file__).resolve().parents[1];O=R/'results/stage4_upgrade_v1';s=json.loads((O/'submission/statistics.json').read_text());d=json.loads((O/'decision.json').read_text())
items={
 'development':('Multi-reference calibration',s['development'],'18 declared points, three seeds per reference. Each run is energy optimized; ED only evaluates. See seed_selected_stability.csv for whole-selector reproducibility, not best-seed success.','run_upgrade.py --task development'),
 'heldout':('Frozen held-out evaluation',s['heldout'],'48 half-step coordinates frozen before development. No ED-driven retraining. Failures are listed with all acceptance metrics.','run_upgrade.py --task heldout'),
 'map':('Matched N8 full map',s['matched'],'420 positive-field descriptive coordinates, B3/B4 at three prescribed p. Historical B0 reused unchanged. Global and common-pass statistics differ; neither is classification accuracy.','run_upgrade_noise.py --task map'),
 'n12':('Twelve-qubit circuits',{'preparation':s['n12'],'noise':s['n12_noise']},'60 new N12 preparations and12 representative exact-density simulations at each of three p. No real hardware. Full matrix spectrum is not computed for every N12 density; validated CPTP gate evolution, trace and Hermiticity are checked.','run_upgrade_n12_noise.py'),
 'detection':('Three diagnostic mechanisms',s['detection'],'D1 observables, D2 squared Uhlmann on noisy slices, D3 frozen PCA/clustering. Analytic controls, Binder comparison, fixed branches and whole-bitstring shot sensitivity are saved. No independent finite-grid phase truth: error rates are undefined, not zero. See mechanism_comparison.json and comparison.csv.','run_upgrade_detection.py'),
 'mitigation':('Equal-shot ZNE and symmetry verification',s['mitigation'],'15 coordinates, two p, folds1/3/5,30 SV measurement settings, total10k/100k shots and32 independent repetitions. Values are unclipped. Target is own clean circuit; bias, variance and MSE are distinct.','run_upgrade_mitigation.py'),
 'floating':('Large-OBC floating evidence',d['bonus']['floating'],'98 unique MPS solves including small-model validation;39 coarse-index and66 refine-index references overlap. N32/64/96;chi64/128/256;two center initializations. Three centers satisfy transparent post-computation evidence criteria, not exact continuous phase boundaries. See evidence_grading.json, convergence_comparison.json and small_periodic_bridge.json.','run_upgrade_floating.py --task refine'),
 'dynamics':('Second-order quench dynamics',s['dynamics'],'252 configurations,11 public times, two fixed product initial states. Exact evolution isolates Trotter error. Frozen time means and held-out h=.6,1.4 descriptive static association are in static_association.json; four held-out coordinates do not validate a phase classifier.','run_upgrade_dynamics.py'),
 'branches':('Actual structure/compilation switch audit',json.loads((O/'submission/branch_summary.json').read_text()),'57 actual neighboring structure pairs. Transport uses explicit fixed-structure energy refits at common coordinates; this is not a pre-existing scan chain or merely an opposite-direction comparison. Both parameter and output hashes retained.','run_upgrade_b4_branches.py'),
 'fixed_branches':('Fixed-structure response controls',{'points':120,'noise_configs':360},'Two frozen structure anchors per kappa,20 fields. All local peaks and nested steps retained. Peak validation uses surrounding four-node preparation support; grid resolution intervals are not confidence intervals. Qualified kappa=.3 case has no resolved shift.','run_upgrade_fixed_branches.py'),
 'ablation':('Method-factor and compilation ablations',s['factor_ablation'],'Includes independent23-CNOT pilot, two-site pool, bounded matched-call HVA, pruning/reoptimization, same-state compilation direction/commuting order, and literal single-error injection. Extra noisy evaluations are charged. Pilot input ZIP unavailable, so no original-file reproduction claim.','run_upgrade_ablation.py'),
}
for name,(title,data,qualification,command) in items.items():
 python='.venv-tn/bin/python' if name=='floating' else '.venv/bin/python'
 (O/name/'REPORT.md').write_text('# '+title+'\n\nDisposition: newly_executed, except explicitly historical B0/ED inputs.\n\n'+qualification+'\n\n```json\n'+json.dumps(data,indent=2)+'\n```\n\nReproduce from project root, retaining frozen hashes/deadline:\n\n```sh\n'+python+' scripts/'+command+'\n```\n\nFull provenance and code/input hashes: ../metadata.json and ../verification/.\n')
print('Workpackage reports written',len(items))
