"""Editable report/deck generation from one release statistics source."""
from pathlib import Path
import json,textwrap,sys
from reportlab.pdfgen import canvas
from reportlab.lib.colors import HexColor
from reportlab.platypus import Paragraph
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.utils import ImageReader
from pptx import Presentation
from pptx.util import Inches,Pt
from pptx.dml.color import RGBColor
R=Path(__file__).resolve().parents[1];S=json.loads((R/'figures/release_statistics.json').read_text());F=R/'figures'
b=S['b0_b3'];q=lambda p,m:next(r for r in S['equal_resource'] if (r['mode'],r['budget'],r['p'],r['method'])==('equal_gate',100000,p,m))
window_score=lambda m: next(r for r in S['windows'] if (r['mode'],r['budget'],r['p'],r['method'])==('equal_shots',100000,.05,m))['frozen_matching_window_equivalents']
reduction={p:100*(1-q(p,'zne_quadratic')['MSE_ED']/q(p,'raw')['MSE_ED']) for p in [.01,.05]}
low={r['method']:r for r in S['extensions'] if r['cohort']=='low_field_confirmation'};n12={r['method']:r for r in S['extensions'] if r['cohort']=='n12'}
title='Noise-Aware ANNNI Phase Diagnostics'
subtitle='Low-CNOT preparation, error mitigation, and their limits'
paras=[
('Model and approach', 'We study the periodic axial next-nearest-neighbor Ising chain H = -sum ZZ(nn) + kappa sum ZZ(nnn) - h sum X, J1=1. Competing interactions complicate state preparation and phase identification at low field. We evaluate state accuracy and observable errors separately from the evidence for phase boundaries. The N=8 circuits cover 420 positive-field coordinates. N=12 circuits and larger matrix-product-state (MPS) calculations with open boundaries extend the study across system sizes and boundary conditions.'),
('Preparation, noise and diagnostics','B0 is a fixed six-layer Hamiltonian variational ansatz. B3 adaptively grows energy-optimized Pauli rotations from multiple reference states and selects a circuit using a frozen energy/resource rule. After every executed CNOT, its target receives D_p(rho)=(1-p)rho+p/3(XrhoX+YrhoY+ZrhoZ). This includes CNOTs used for reference preparation and folding. The explicit gate implementation preserves the recorded connectivity and wire-0-MSB convention. We measure the full C(r), all discrete structure factors and Mx. Frozen D3 uses PCA and clustering to classify resemblance to reference patterns; it supplies a diagnostic label rather than independent phase truth.'),
('Fewer CNOTs, lower preparation coverage',f"Replacing B0 with B3 reduces median CNOTs from {b[0]['B0_median_CNOT']:.0f} to {b[0]['B3_median_CNOT']:.0f}, while ideal joint preparation passes fall from {b[0]['B0_joint_pass']}/420 to {b[0]['B3_joint_pass']}/420. At p=.01, the mean pointwise maximum correlation error falls from {b[1]['B0_mean_max_C_error']:.4f} to {b[1]['B3_mean_max_C_error']:.4f}, with improvement at {b[1]['B3_better']}/420 coordinates. These values measure correlation reconstruction, not phase-classification accuracy. A joint pass requires delta e <= .001 per spin, C/SF/Mx errors <= .02 and squared ED fidelity >= .99."),
('Comparison at equal CNOT-shots','We compare raw estimates, quadratic zero-noise extrapolation (ZNE) and global-X symmetry verification (SV) on 45 fixed coordinates, with 32 measurement repeats. Each method has the same per-coordinate budget G=sum(shots x literal CNOTs). Raw and SV use 100,000 shots; ZNE uses 33,334 across folds 1/3/5, with weights 15/8,-5/4,3/8. SV estimates (O+OP)/(1+P) using all required signed joint settings. Matching G controls CNOT-weighted shot cost. Measurement settings and one-qubit costs remain outside this budget.'),
('Observable errors and the zero-noise control',f"The ED-target MSE gives equal weight to the same 17 components: eight C, eight Fourier-related SF, and Mx. At p=.01, raw/ZNE/SV give {q(.01,'raw')['MSE_ED']:.8f}/{q(.01,'zne_quadratic')['MSE_ED']:.8f}/{q(.01,'sv')['MSE_ED']:.8f}; at p=.05 they give {q(.05,'raw')['MSE_ED']:.8f}/{q(.05,'zne_quadratic')['MSE_ED']:.8f}/{q(.05,'sv')['MSE_ED']:.8f}. ZNE lowers mean MSE by {reduction[.01]:.2f}% and {reduction[.05]:.2f}%, respectively, and improves the coordinate-mean error at all 45 points. At p=0, it worsens all 45. The reduction in bias comes with higher sampling MSE. Only six points have independent interior labels, so the 45-point result measures observable reconstruction rather than phase accuracy."),
('Response-feature matching',f'We execute all six 17-point windows at kappa=0,.3,.45,.5,.55,.8 using identical grids and frozen matching rules. The .5 reference fails the frozen peak-selection criterion. The other five references describe finite-size RN features, not thermodynamic critical points. At p=.05 and 100k equal shots, raw estimates match {window_score("raw"):g}/5 window equivalents across repeats, compared with {window_score("zne_quadratic"):g}/5 for ZNE. The records retain endpoint domination, competing peaks, preparation errors and branch sensitivity. These results show why observable MSE and finite-size feature matching need separate evaluation.'),
('Low-field preparation and transfer',f"H6 combines physical and domain-wall candidates in a frozen union. On the N8 low-field cohort, candidate availability rises from {low['B3']['candidate_exists']}/48 to {low['H6']['candidate_exists']}/48 and selected joint passes from {low['B3']['joint_pass']}/48 to {low['H6']['joint_pass']}/48. This improvement costs more: median CNOTs rise from {low['B3']['median_CNOT']:.0f} to {low['H6']['median_CNOT']:.0f}, and objective calls increase by {low['H6']['nfev']/low['B3']['nfev']:.2f}x. On the N12 difficult/control transfer set, B3 passes {n12['B3']['joint_pass']}/36 and H6 passes {n12['H6']['joint_pass']}/36. H6 therefore improves the N8 low-field result at greater cost but reduces the pass count on this N12 cohort."),
('Floating-phase search and extensions','The controlled kappa=.8 OBC slice supports an antiphase sample at h=.3 and a paramagnetic-side sample at h=.7. At h=.4/.425, the size, entropy and Friedel diagnostics disagree. The final evidence contains zero supported floating samples and zero established transition brackets. Bond-dimension convergence checks numerical stability; phase identification depends on gap and correlation-length scaling. The chi=512 run reached its time limit, which provides no basis for excluding a phase. The archived dynamics quantify Trotter and noise effects. The notebook also contains the multiple-detector and N12 experiments, all drawn from the frozen dataset.'),
('Conclusions and reproduction','Lower-gate preparation and cost-controlled mitigation improve observable reconstruction in these experiments. Reliable phase-boundary inference remains a separate requirement. We distinguish R0 region interiors, RN same-size diagnostics and Rlarge evidence qualified by system size. The main figures and statistics rebuild from the bundled numerical data and joint counts. The package also includes lightweight explicit-gate and SDK checks, with separate results for V1 deterministic saved-data verification, V2 physical checks and V3 exact random replay under its specified environment contract.'),
]
refs='References: Q-SITE 2026 Scientific Track, snapshot 57f9a537 (local upstream/); Tang et al., qubit-ADAPT-VQE, arXiv:1911.10205; ANNNI tensor-network study, arXiv:2402.11022; floating-phase DMRG, arXiv:cond-mat/0702676; symmetry verification, arXiv:1807.10050. Published XX/Z conventions are related to ZZ/X by local Hadamards; boundaries and sizes are not interchangeable.'
(R/'report.md').write_text('# '+title+'\n\n'+subtitle+'\n\nTeam hamster: Shupei Zhang, Yangxin Zhou, Michael Li, Kathy Chen\n\n'+'\n\n'.join('## '+a+'\n\n'+b for a,b in paras)+'\n\n'+refs+'\n')
(R/'report_source.md').write_bytes((R/'report.md').read_bytes())
# Fixed three-page article, comfortable body text and informative full-width figures.
c=canvas.Canvas(str(R/'report.pdf'),pagesize=(595,842));c.setTitle(title);c.setAuthor('Team hamster; Shupei Zhang, Yangxin Zhou, Michael Li, Kathy Chen')
style=ParagraphStyle('body',fontName='Helvetica',fontSize=9.6,leading=12.8,textColor=HexColor('#263745'),spaceAfter=7)
small=ParagraphStyle('caption',parent=style,fontSize=8.1,leading=10.4)
def text(s,y,size=9.6,width=507):
 st=style if size==9.6 else small;p=Paragraph(s,st);w,h=p.wrap(width,1000);p.drawOn(c,44,y-h);return y-h-16
def head(s,y):c.setFillColor(HexColor('#155D75'));c.setFont('Helvetica-Bold',12);c.drawString(44,y,s);return y-9
def pic(name,y,width=507):
 img=ImageReader(str(F/(name+'.png')));w,h=img.getSize();height=width*h/w;c.drawImage(img,44,y-height,width,height);return y-height-9
def foot(num):c.setFont('Helvetica',8);c.setFillColor(HexColor('#5C6D79'));c.drawString(44,24,'Q-SITE Scientific Track | Frozen numerical research | Team hamster');c.drawRightString(552,24,str(num));c.showPage()
c.setFillColor(HexColor('#163C51'));c.setFont('Helvetica-Bold',21);c.drawString(44,801,title);c.setFont('Helvetica',12);c.drawString(44,781,subtitle);c.setFont('Helvetica-Bold',9);c.drawString(44,761,'Team hamster | Shupei Zhang, Yangxin Zhou, Michael Li, Kathy Chen')
y=741
for a,b in paras[:2]:y=head(a,y);y=text(b,y)
y=pic('phase_comparison',y);y=text('Figure 1. N8 PBC, h>0. The ED reference and raw B3 results at three noise levels use frozen D3 and the same color scale. Colors show phase-like estimates; crosses mark failed preparations. The notebook shows reference coverage separately.',y,8)
y=head(paras[2][0],y);y=text(paras[2][1],y);y=pic('resource_tradeoff',y)
assert y>35,y
foot(1);y=797
for a,b in paras[3:5]:y=head(a,y);y=text(b,y)
y=pic('equal_resource',y);y=text('Figure 2. Results include all 45 coordinates. Each value averages 32 repeats, with the original equal weighting of related C/SF components. The panels compare experiments matched by shots and by CNOT-shots.',y,8)
y=head(paras[5][0],y);y=text(paras[5][1],y);y=pic('window_example',y);y=text('Figure 3. The prespecified kappa=.8 window at p=.05 uses exact expectations to isolate noise and preparation effects. All endpoints and both competing response features are retained. Peaks are not selected afterward by proximity to the reference.',y,8)
assert y>35,y
foot(2);y=797
for a,b in paras[6:8]:y=head(a,y);y=text(b,y)
y=pic('extensions',y);y=pic('floating_evidence',y)
y=head(paras[8][0],y);y=text(paras[8][1],y);y=text(refs,y,8)
assert y>35,y
foot(3);c.save()
# Slide content and notes derive from same statistics. All text is editable.
b=S['b0_b3']
slides=[
 dict(title='Noise-Aware ANNNI\nPhase Diagnostics',sub=subtitle,body='Q-SITE 2026 / Scientific Track\nTeam hamster\nShupei Zhang, Yangxin Zhou, Michael Li, Kathy Chen',fig='resource_tradeoff',note='We study how quantum state preparation and noise affect reconstruction of the ANNNI phase diagram. The central result is a tradeoff: fewer entangling gates improve noisy correlations, and mitigation helps under a genuinely matched gate-weighted measurement budget. But neither improvement alone certifies a phase boundary. We keep the failed preparations, detector rejections and floating-scan results in the submission. The notebook contains the full numerical evidence and a lightweight circuit check.',seconds=40),
 dict(title='Model and evidence layers',sub='Periodic N8/N12 circuits; large-size OBC evidence kept separate',body='H = -sum ZZ(nn) + kappa sum ZZ(nnn) - h sum X\nEvery CNOT: target-only depolarizing channel\nR0 interiors / RN finite-size features / Rlarge trends',fig='slide_reference',note='The Hamiltonian has ferromagnetic nearest-neighbor coupling, competing next-nearest-neighbor coupling and a transverse field. We use periodic boundaries for the small circuits. Noise follows every literal CNOT, on its target only, with the same specified channel at all three noise strengths. Reference preparation and folding count as gates. Three evidence layers prevent a detector from grading itself: supported interiors, same-size exact-diagonalization features, and larger-system evidence. Our observables retain every distance and momentum, including the self-correlation background.',seconds=45),
 dict(title='Fewer gates, different tradeoffs',sub='B0 fixed six-layer HVA -> B3 multi-reference adaptive preparation',body=f"Median CNOTs: {b[0]['B0_median_CNOT']:.0f} -> {b[0]['B3_median_CNOT']:.0f}\nIdeal joint passes: {b[0]['B0_joint_pass']}/420 -> {b[0]['B3_joint_pass']}/420\np=.01 correlation error improves at {b[1]['B3_better']}/420 points",fig='resource_tradeoff',note=f"B0 is the original fixed six-layer Hamiltonian variational ansatz. B3 starts from several physical references and grows energy-optimized Pauli rotations, then uses a frozen energy and resource rule. The median CNOT count is halved, from 192 to 96. Ideal joint preparation coverage drops from 407 to 385 out of 420, so the method does not win on every metric. At noise probability one percent, mean maximum correlation error falls from {b[1]['B0_mean_max_C_error']:.4f} to {b[1]['B3_mean_max_C_error']:.4f}, with improvement at 402 coordinates. This is an observable result, not phase-label accuracy.",seconds=45),
 dict(title='Three noise levels, one diagnostic',sub='Frozen D3; exact expectations; identical 420-point grid',body='Colors: estimated phase-like regions\nCrosses: ideal preparation failed\nUnassigned and degraded are separate classes',fig='slide_phases',note='These are the required three noise maps, alongside the same detector applied to ED data. The method, grid and legend remain fixed across noise levels. The colors show resemblance to physical patterns, not independently validated truth at every coordinate. Crosses indicate failed ideal preparation without hiding the label. Our notebook separately displays single-repeat finite-shot maps and equal-shots mitigation maps. It also shows where independent region labels exist. We never extend the smaller equal-resource cohort into a full equal-resource map.',seconds=45),
 dict(title='Mitigation at equal CNOT-shots',sub='45 fixed coordinates / 32 repeats / unchanged 17-component MSE',body=f"G = 100,000 x original CNOT count\nRaw / SV: 100k shots; ZNE: 33,334\nZNE MSE decrease: {reduction[.01]:.2f}% / {reduction[.05]:.2f}%",fig='equal_resource',note=f"Equal shot counts alone favor extrapolation with more noisy gates. We therefore match the sum of shots times literal CNOTs at each coordinate. Raw and symmetry verification use one hundred thousand shots, whereas quadratic ZNE uses thirty-three thousand three hundred and thirty-four shots shared across the three folds. The integer gate-weighted costs match exactly. At p=.01 and .05 the mean ED-target MSE falls by {reduction[.01]:.2f} and {reduction[.05]:.2f} percent. Each of the 45 coordinate means improves. ZNE worsens all 45 at zero noise. It reduces bias while increasing sampling error, and only six coordinates have independent phase-interior labels.",seconds=55),
 dict(title='Better observables, unstable features',sub='Six complete 17-point windows; five references pass peak selection',body='kappa=.5 fails reference peak selection\nEndpoints, multiple peaks and branch effects retained\nMatching is finite-size evidence, not a phase certificate',fig='window_example',note='The prespecified kappa point eight window illustrates the distinct outcomes of observable reconstruction and response-feature matching. These curves use exact expectations so shot fluctuations cannot explain every failure. All six windows were actually executed. Five reference features are resolvable; the kappa point five reference fails the frozen peak-selection criterion. At strong noise, the equal-shots raw result matches roughly three of those five windows when averaged over measurement repeats, and extrapolation does not improve that aggregate. We retain endpoint and multiple-peak warnings, preparation failures and real same-coordinate branch comparisons. A match with no listed warning is still not proof of a thermodynamic transition.',seconds=50),
 dict(title='Extensions expose the limits',sub='H6 is a physical/domain-wall union, not the six-layer HVA',body=f"N8 low-field passes: {low['B3']['joint_pass']}/48 -> {low['H6']['joint_pass']}/48, with more resources\nN12 difficult/control transfer: {n12['B3']['joint_pass']}/36 vs {n12['H6']['joint_pass']}/36\nDynamics, multiple detectors and mitigation retained",fig='extensions',note='The newer physical and domain-wall construction improves selected joint passes in the independent low-field confirmation subset, from 27 to 37 out of 48. However, median CNOTs increase from 32 to 127 and objective calls increase by about seven and a half times. H6 therefore is not an equal-cost universal winner. Its transfer to the N12 difficult/control set is weaker than B3. The five extension topics remain in the package: larger circuits, multiple detectors, mitigation, dynamics, and the floating-phase search. The negative transfer result is preserved rather than removed from the final story.',seconds=45),
 dict(title='What the evidence supports',sub='A reproducible observable result with explicit phase-diagram limits',body='Lower-CNOT preparation helps noisy correlations\nEqual-resource ZNE reduces bias, not every failure\nZero supported floating samples',fig='floating_evidence',note='The controlled large-system slice supports an antiphase control at field point three and a paramagnetic-side control at point seven. Fields point four and point four two five have conflicting size, entropy and Friedel results. The final evidence contains zero supported floating samples and zero established transition brackets. A timed-out high-bond-dimension continuation is not evidence against a phase. Our conclusion is therefore specific: lower-gate preparation and resource-controlled mitigation improve observable reconstruction, while reliable boundary inference needs stronger evidence. The submission ships saved joint counts, gate tables, reproducible figures, and separate deterministic, physical and random-replay checks.',seconds=45)
]
if "--text-and-report-only" not in sys.argv:
 prs=Presentation();prs.core_properties.author='Team hamster; Shupei Zhang, Yangxin Zhou, Michael Li, Kathy Chen';prs.slide_width=Inches(13.333);prs.slide_height=Inches(7.5)
 navy=RGBColor.from_string('173F54');gray=RGBColor.from_string('536772')
 def box(sl,text,x,y,w,h,size=18,bold=False,color=navy):
  s=sl.shapes.add_textbox(Inches(x),Inches(y),Inches(w),Inches(h));tf=s.text_frame;tf.word_wrap=True;tf.margin_left=0;tf.margin_right=0;tf.margin_top=0
  for i,line in enumerate(text.split('\n')):
   p=tf.paragraphs[0] if i==0 else tf.add_paragraph();p.text=line;p.font.name='Arial';p.font.size=Pt(size);p.font.bold=bold;p.font.color.rgb=color;p.space_after=Pt(7)
  return s
 for i,d in enumerate(slides):
  sl=prs.slides.add_slide(prs.slide_layouts[6]);box(sl,d['title'],.55,.35,12.2,1.45 if i==0 else .72,36,True);y=1.9 if i==0 else 1.2;box(sl,d['sub'],.57,y,12.1,.6,20,False,gray)
  box(sl,d['body'],.6,y+.72,12.0,1.45,18)
  # Figure fit preserves aspect ratio; ample room for citations/footer.
  from PIL import Image
  im=Image.open(F/(d['fig']+'.png'));iw,ih=im.size;maxw,maxh=12.0,2.85 if i==0 else 3.30;w=min(maxw,maxh*iw/ih);h=w*ih/iw;py=3.75 if i==0 else 3.25
  shape=sl.shapes.add_picture(str(F/(d['fig']+'.png')),Inches((13.333-w)/2),Inches(py),width=Inches(w),height=Inches(h));shape._element.nvPicPr.cNvPr.set('descr',d['sub'])
  box(sl,f'Frozen research | Source: release_statistics.json + bundled numerical curves | {i+1}/8',.58,7.05,12,.3,10,False,gray)
  sl.notes_slide.notes_text_frame.text=d['note']
 prs.save(R/'presentation.pptx')
(R/'speaker_notes.md').write_text('# Speaker notes\n\nTeam hamster — Shupei Zhang, Yangxin Zhou, Michael Li, Kathy Chen\n\nSpeaking plan: '+str(sum(x['seconds'] for x in slides))+' seconds (6 min 10 sec).\n\n'+'\n\n'.join(f"## Slide {i+1}: {d['title'].replace(chr(10),' ')} ({d['seconds']} seconds)\n\n{d['note']}" for i,d in enumerate(slides)))
(R/'provenance/document_content.json').write_text(json.dumps(dict(title=title,subtitle=subtitle,paragraphs=paras,slides=slides,statistics_source='figures/release_statistics.json'),indent=2))
print('report pages=3; slide content=8')
