"""Same-named finite-size feature matching; complete denominators and failures."""
import numpy as np
from .stage6_diagnostics import peaks_and_primary,response_curves
def compare(h,values,n,name,reference,max_position_error=.05):
 y=response_curves(h,values,n)[name];result=peaks_and_primary(h,y);p=result['primary'];r=reference['primary'];refok=reference['resolvable'];estimateok=result['resolvable'];error=float(p['coordinate']-r['coordinate']) if p and r else None
 finite=np.flatnonzero(np.isfinite(y));maximum=int(finite[np.argmax(y[finite])]) if len(finite) else None
 return dict(reference_resolvable=refok,algorithm_estimatable=estimateok,matched=bool(refok and estimateok and abs(error)<=max_position_error),position_error=error,position_error_unconditional_primary=error,raw_maximum_coordinate=float((h[maximum]+h[maximum+1])/2) if maximum is not None else None,raw_maximum_endpoint=bool(maximum in [0,len(y)-1]) if maximum is not None else None,interval_width=float(p['interval_high']-p['interval_low']) if p else None,result=result,reference=reference,status='reference_unresolved' if not refok else 'algorithm_unresolved' if not estimateok else 'feature_mismatch' if abs(error)>max_position_error else 'same_named_RN_feature_matched',match_scope='Named response feature only, not independently established thermodynamic transition',curve=y.tolist())
def denominator(rows):
 requested=len(rows);ref=sum(r['reference_resolvable'] for r in rows);estimated=sum(r['reference_resolvable'] and r['algorithm_estimatable'] for r in rows);matched=sum(r['matched'] for r in rows);errors=[abs(r['position_error']) for r in rows if r['matched']];all_errors=[abs(r['position_error']) for r in rows if r['position_error'] is not None and r['reference_resolvable']]
 return dict(requested=requested,reference_resolvable=ref,reference_fraction=ref/requested if requested else None,algorithm_estimatable_given_reference=estimated,algorithm_fraction_given_reference=estimated/ref if ref else None,matched=matched,matched_fraction_given_reference=matched/ref if ref else None,mean_matched_error=float(np.mean(errors)) if errors else None,worst_matched_error=max(errors) if errors else None,worst_all_primary_error=max(all_errors) if all_errors else None,missing_or_mismatch=requested-matched)
